server:
  port: 80
  ssl:
    enabled: false
  servlet:
    context-path: /api
  max-http-header-size: 1000000
logging:
  config: classpath:logback.xml
spring:
  application:
    name: thumbnail
  profiles: dev,test
  datasource:
    url: jdbc:h2:file:./db/doqmind;INIT=CREATE SCHEMA IF NOT EXISTS DOQMIND
    username: sa
    password:
    driver-class-name: org.h2.Driver
    dialect: "org.hibernate.dialect.H2Dialect"
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: doqmind
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    non-blocking-redelivery: true
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
      pool:
        max-sessions-per-connection: 500
      time-between-expiration-check: -1
      use-anonymous-producers: true

thumbnail:
  thumbnail-topic: VirtualTopic.thumbnail-topic
  container-url: https://stdoqmindsandbox.blob.core.windows.net/
  connection-string: DefaultEndpointsProtocol=https;AccountName=stdoqmindsandbox;AccountKey=voXgdF+pu+cO0MxHIsRtQxVqRQrKXOPZk9UvTi/nDgX8ejoIu+RZj8g+WAcgAeJxyqOqfbK9FWza+AStc1J4JQ==;EndpointSuffix=core.windows.net
  container: assets