server:
  port: 8449
  ssl:
    enabled: false
  servlet:
    context-path: /api
  max-http-header-size: 1000000
logging:
  config: classpath:logback.xml
spring:
  application:
    name: thumbnail
  profiles: dev,test
  datasource:
    url: jdbc:mysql://localhost:3306/doqmind
    username: root
    password: caherline
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: doqmind
  jms:
    pub-sub-domain: true

thumbnail:
  thumbnail-topic: VirtualTopic.thumbnail-topic
  container-url: https://stdoqmindsandbox.blob.core.windows.net/
  connection-string: DefaultEndpointsProtocol=https;AccountName=stdoqmindsandbox;AccountKey=voXgdF+pu+cO0MxHIsRtQxVqRQrKXOPZk9UvTi/nDgX8ejoIu+RZj8g+WAcgAeJxyqOqfbK9FWza+AStc1J4JQ==;EndpointSuffix=core.windows.net
  container: assets